server:
  port: 8085
feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持
spring:
  elasticsearch:
    rest:
      uris:
        - http://localhost:9200
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.dianping.follow.domain.po # 别名扫描包
  type-handlers-package: com.hmdp.config.BooleanCharTypeHandler
logging:
  level:
    com.dianping.follow: debug
files:
  upload:
    path: icons\