server:
  port: 8080

spring:
  application:
    name: dp-common
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://182.92.103.35:3306/hmdp?serverTimezone=GMT%2b8
    username: root
    password: sing.11
  redis:
    host: 150.158.179.162
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

  elasticsearch:
    rest:
      uris:
        - http://localhost:9200
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  rabbitmq:
    host: 182.92.103.35 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: 123 # 密码
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
  type-handlers-package: com.hmdp.config.BooleanCharTypeHandler
logging:
  level:
    com.hmdp: debug
files:
  upload:
    path: icons\